# mkdocs.yml

# Project information
site_name: swcat Documentation
site_url: https://dnswlt.github.io/swcat/ # Replace with your actual URL
site_description: 'Documentation for the swcat software catalog.'

# Theme configuration
# We're using the popular "Material for MkDocs" theme here.
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.indexes

# The navigation structure
nav:
  - 'Home': 'index.md'
  - 'Getting started': 'getting-started.md'
  - 'User guide':
    - 'Overview': 'user-guide/index.md'
    - 'Catalog': 
      - 'user-guide/catalog/index.md'
      - 'Metadata': 'user-guide/catalog/metadata.md'
      - 'Entity References': 'user-guide/catalog/entity-references.md'
      - 'Domain': 'user-guide/catalog/domain.md'
      - 'System': 'user-guide/catalog/system.md'
      - 'Component': 'user-guide/catalog/component.md'
      - 'Resource': 'user-guide/catalog/resource.md'
      - 'API': 'user-guide/catalog/api.md'
      - 'Group': 'user-guide/catalog/group.md'
    - 'Configuration': 'user-guide/configuration.md'
    - 'Custom content': 'user-guide/custom-content.md'
    - 'Sidecar extensions': 'user-guide/sidecar-extensions.md'
    - 'Plugins': 'user-guide/plugins.md'
    - 'Remote catalogs': 'user-guide/remote-catalog.md'
    - 'Query syntax': 'user-guide/query-syntax.md'
    - 'JSON API': 'user-guide/json-api.md'

# Extensions (optional but recommended for a better experience)
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
